device: cuda
dataset:
    folder: "/home/serk0/Business/new_live/VoxCeleb1/"
    faces_structure: "Faces/{0}/1.6/{1}/*"
    identity_structure: "Faces/"
    video_structure: "Faces/{0}/1.6/"
    n_target_images: 4
    image_size: 128
preprocess:
    folder: "/home/serk0/Business/new_live/VoxCeleb1/"
    dataset_structure: "Faces/*/*/*/*"
    landmark_type: "3D"
    device: "cpu"
training:
    batch_size: 16
    discriminator:
        clipping: 1
        lr: 0.0002
    generator:
        clipping: 1
        lr: 0.00005
    logging:
      log_step: 10
    num_epoch: 100
    number_indentities_in_test: 5
    samples:
      sample_step: 10
      saving_path: "../generated_images/img_{}.jpg" 
    model_saving:
      step: 300
      path: "../checkpoints/model_{}.pt"
    random_seed: 2021
    shuffle: True
    wandb:
      project: 'MarioNet'
      name: 'First_run'
model:
  # MarioNet parameters grouped by main network components.
  # Groups are named after implementation classnames (i.e. CamelCase).
  # Other keys should use snake_case.
  TargetEncoder:
    # 'The number of channels is doubled (or halved) when the output is downsampled
    #   (or upsampled). The minimum number of channels is set to 64 and the maximum
    #   number of channels is set to 512 for every layer.'
    image_channels: 3
    landmarks_channels: 3
    downsampling_channels:
      - 64
      - 128
      - 256
      - 512
      - 512
      - 512
    upsampling_channels:
      - 512
      - 512
      - 512
      - 256
      - 128
  Decoder:
    channels:
      - 512
      - 512
      - 256
      - 128
      - 64
    output_channels: 3
  DriverEncoder:
    landmarks_channels: 3
    hidden_features_dim:
      - 64
      - 128
      - 256
      - 512
      - 512
  Blender:
    input_target_feature_map_dim: 512
    driver_feature_dim: 512
    target_feature_dim: 512
    attention_feature_dim: 256
  PositionalEncoding:
    driver_feature_size:
      - 512
      - 228
      - 228
    target_feature_size:
      - 4
      - 512
      - 228
      - 228
  Discriminator:
    image_channels: 3
    landmarks_channels: 3
    channels:
      - 64
      - 128
      - 256
      - 512
      - 512
    spectral_norm: True